name: Tests

on:
  push:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Set up test environment
        run: |
          echo "Database.Url=${{ secrets.DATABASE_URL }}" > internal/backend/database/.env.test
          echo "Database.AuthToken=${{ secrets.DATABASE_AUTHTOKEN }}" >> internal/backend/database/.env.test
          
      - name: Test
        run: go test -v ./...
